---
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    dir: ./cmd/respond
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm

dockers:

  -
    goos: linux
    goarch: amd64
    image_templates:
      - "sysant/respond:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"

    dockerfile: Dockerfile
    use: buildx
  -
    goos: linux
    goarch: arm64
    image_templates:
      - "sysant/respond:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"

    dockerfile: Dockerfile
    use: buildx

  -
    goos: linux
    goarch: arm
    image_templates:
      - "sysant/respond:{{ .Tag }}-arm"
    build_flag_templates:
      - "--platform=linux/arm"

    dockerfile: Dockerfile
    use: buildx

docker_manifests:
  - name_template: sysant/respond:{{ .Version }}
    image_templates:
      - sysant/respond:{{ .Version }}-amd64
      - sysant/respond:{{ .Version }}-arm64
      - sysant/respond:{{ .Version }}-amd
  - name_template: sysant/respond:latest
    image_templates:
      - sysant/respond:{{ .Tag }}-amd64
      - sysant/respond:{{ .Tag }}-arm64
      - sysant/respond:{{ .Tag }}-amd


archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
