version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "respond-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12r6r0p95bti4"
s3_prefix = "respond-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
