---

name: Go

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

jobs:
  build:

    env:
      # Enable experimental to allow pushing Manifests
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # fetch depth 0 required for Changelog to be correctly generated
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Test
        run: go test -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v6.2.1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
